version: "3"

services:
  quake3:
    image: colega/q3-server
    restart: always
    ports:
     - 27960:27960/udp
    volumes:
     - ./server.cfg:/home/ioq3srv/ioquake3/osp/server.cfg
     - ./logs/games.log:/home/ioq3srv/.q3a/osp/games.log

  ng-quake3-be:
    environment:
       - Q3SERV_HOST:quake3
    image: colega/q3-server-be
    build: ./ng-quake3-be/
    restart: always

  ng-quake3-fe:
    restart: always
    image: colega/q3-server-fe
    ports:
     - 8080:8080

networks:
  default:
    external:
      name: local-network
